### ISSUE TITLE
icon 装饰小图标解决方案

### ISSUE THREAD

**Issue by ziven27** [ziven27/blog#14]
![-1_spec](https://cloud.githubusercontent.com/assets/7261176/19145524/e5a10c3a-8be1-11e6-9912-1f4d71524971.png)

对于装饰性的图标，我一般推荐采用`<i>`标签。因为`<i>`标签本身就是为这个而生的。
> `<i> `标签定义与文本中其余部分不同的部分，并把这部分文本呈现为斜体文本。在没有其他元素可以使用时，比如 `<b>`, `<cite>`, `<dfn>`, `<em>`, `<q>`, `<small>`, `<strong>`，请使用` <i> `标签。

怎么给它添加图片呢。简单的说就是要给一个容器设定一个高宽，然后在这个高宽中设定一个背景图片。示意图的代码我们可以改成以下形式。
```html
<link rel="stylesheet" href="style/i.css">
<!-- 分割线 -->
<a href="" title="facebook"><i class="i-share-1">facebook</i></a>
<a href="" title="twitter"><i class="i-share-2">twitter</i></a>
<a href="" title="google"><i class="i-share-3">google</i></a>
```
```css
/* style/i.css */
.i-share-1, .i-share-2, .i-share-3{ 
  display: inline-block; /*行内元素设定这个之后才能设定高宽*/
  background-repeat: no-repeat; /*background默认是会平铺的所以需要用这个去掉*/
  border:2px solid #fff;
  width: 31px; 
  height: 31px; 
}
.i-share-1{ background-image: url(../img/share/1.png); }
.i-share-2{ background-image: url(../img/share/2.png); }
.i-share-3{ background-image: url(../img/share/3.png); }
```
新建了一个同名i.css文件，我把公用的样式写到了一起减少了代码，但是像`display`和 `background-repeat`，对于其它的图标也是适用的。把所有图标样式写到一起显然是不方便管理的。所以我们需要把这些共用的样式都通用出来。
```html
<a href="" title="facebook" class="i i-share i-share-1">facebook</a>
<a href="" title="twitter" class="i i-share i-share-2">twitter</a>
<a href="" title="google" class="i i-share i-share-3">google</a>
```
```css
/* style/i.css */
i, .i{ display: inline-block; background-repeat: no-repeat; }
.i-share{ width: 31px; height: 31px; border:2px solid #fff; }
.i-share-1{ background-image: url(../img/share/1.png); }
.i-share-2{ background-image: url(../img/share/2.png); }
.i-share-3{ background-image: url(../img/share/3.png); }
```
进一步优化之后，为了把i标签的样式复用到其它标签上，我多添加了一个同名的`i`类。这样我们就可以去掉嵌套的i标签。同时我把share的样式也通用了出来，便于以后托展。
> 怎么判断一个代码好还是不好，我觉得主要看后期修改的地方和成本。

到这里我们以为代码写的很不错了，打开页面一看，发现图片被文字挡住了。所以就需要将文字隐藏。
```css
/* style/i.css */
i, .i{ 
  display: inline-block; 
  background-repeat: no-repeat; 
  /*文字隐藏*/
  overflow:hidden;
  line-height:200px; /* 尽量大一点就好 */
}
```
