### ISSUE TITLE
如何判断多行文本超出？

### ISSUE THREAD

**Issue by ziven27** [ziven27/blog#22]
**问：如何实现一个字号为16px行高为28px的文本，最多显示5行，超出5行显示更多？**

答：

``` css
.box{
  max-height:140px;  /* 28px*5 */
  overflow:hidden;  
}
```
用以上代码就可以实现文本最多显示5行。

然而难的是我们要怎么判断在以上代码的情况下，文本高度是超出5行的呢？
